#!/bin/bash
 
# The logic to start up the application is located in this script.
# The application will work only if it binds to $OPENSHIFT_INTERNAL_IP:8080
 
# Install the dependencies
cd $OPENSHIFT_REPO_DIR
$OPENSHIFT_DATA_DIR/bin/npm \
    --cache="$OPENSHIFT_DATA_DIR".npm \
    --tmp=$OPENSHIFT_TMP_DIR install
 
# start the application
nohup $OPENSHIFT_DATA_DIR/bin/node $OPENSHIFT_REPO_DIR/app.js >> $OPENSHIFT_LOG_DIR/app.log 2>&1&
exit 0
