language: node_js
node_js:
- '0.10'
before_install:
  - rm -r node_modules/dpd-jobs
deploy:
  provider: openshift
  user: me@yannisguedel.ch
  password:
    secure: PhafLjgHD3AjAJ/k+qr6e1nS3rFv/nmHZpAoz2EbVegcLt5xfg4Mx8eb6aJnsCJnEav4INnIFNc5d3TRnIDHEtfYDFYleSe/oTrNrmF7VsvP1GsxHw6vGKW1Ic3GKR/InwlYMnZuT1o8jAvNLVo6Yfe/wcT927Iw/lGSKklzMQM=
  app: oevents
  domain: monkeytech
  on:
    branch: master
